using UnityEngine;
using System.Collections;

namespace RFLib
{
	// Enumeration of RFHighScore Event Typs
	public enum RFHighScoreEventType
	{
		RFHIGH_SCORE_NEW,				// New high score
		RFHIGH_SCORE_EDIT_DONE,			// High score edit is complete and saved
		RFHIGH_SCORE_EDIT_UPDATE		// High Score is in edit mode, and an update to the initials happened


	}

	// Event Class; provide information to other game systems that may be interested in high scores collection. i.e.: sound management, fx management
	// High Score Events are generated by RFHighScoreViewer in response to new high scores and high score data editing.
	public class RFHighScoreEventData
	{
		public RFHighScoreEventType EventType  = RFHighScoreEventType.RFHIGH_SCORE_NEW;

		// High score data being worked on
		public RFHighScore			HighScoreData;

		// Gameobjec that is responsible for rendering the high score; MUST have the IRFHighScoreHandler interface
		public GameObject  			HighScoreRenderer;				
	}
}