// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_3000_totems = "CgkI4-bthYYaEAIQDA"; // <GPGSID>
        public const string leaderboard_top_scorers = "CgkI4-bthYYaEAIQBQ"; // <GPGSID>
        public const string achievement_5000_totems = "CgkI4-bthYYaEAIQDQ"; // <GPGSID>
        public const string achievement_9999_totems = "CgkI4-bthYYaEAIQDg"; // <GPGSID>
        public const string achievement_2000_totems = "CgkI4-bthYYaEAIQCw"; // <GPGSID>
        public const string achievement_50_score = "CgkI4-bthYYaEAIQAQ"; // <GPGSID>
        public const string achievement_50000_totems = "CgkI4-bthYYaEAIQDw"; // <GPGSID>
        public const string achievement_100_score = "CgkI4-bthYYaEAIQAw"; // <GPGSID>
        public const string achievement_200_score = "CgkI4-bthYYaEAIQBA"; // <GPGSID>
        public const string achievement_75_score = "CgkI4-bthYYaEAIQAg"; // <GPGSID>
        public const string achievement_99999_totems = "CgkI4-bthYYaEAIQEA"; // <GPGSID>
        public const string achievement_1000_totems = "CgkI4-bthYYaEAIQCg"; // <GPGSID>
        public const string achievement_25_score = "CgkI4-bthYYaEAIQAA"; // <GPGSID>
        public const string achievement_500_totems = "CgkI4-bthYYaEAIQEQ"; // <GPGSID>
        public const string achievement_500_score = "CgkI4-bthYYaEAIQCQ"; // <GPGSID>
        public const string achievement_400_score = "CgkI4-bthYYaEAIQCA"; // <GPGSID>
        public const string achievement_300_score = "CgkI4-bthYYaEAIQBw"; // <GPGSID>

}

